### ISSUE TITLE
Token sniffing method

### ISSUE THREAD

**Issue by GalKar83** [ShonP40/ha-palgate#1]
Seems like the method suggested for sniffing the token isn't working anymore,
therefore I can't set the devices from PalGate in HA.
Is there any other method to get the token?

**Comment by ShonP40** [comment]
Sorry, I don't have any other ways of sniffing that token at the moment.

Read here for more info https://github.com/RoeiOfri/homebridge-palgate-opener/issues/17

**Comment by GalKar83** [comment]
Thanks for replying,
I read the thread you mentioned and  if I understand correctly there is no solution for the tokens right now. 
Therefore, the integration is broken until this issue will be sorted?

**Comment by ShonP40** [comment]
The integration itself is working just fine (I have it running on my Home Assistant instance for almost a year already)

The only part that's broken is generating a token, which isn't technically a part of this repository as I never provided my own token sniffing tool

**Comment by GalKar83** [comment]
I'm aware of the fact that you aren't in charge of the sniffing tool.
At least the tokens you had still working for you.
I will follow that thread hoping it will be resolved sometime.

**Comment by ShonP40** [comment]
Alright, if I ever have more spare time for this, I'll try to create a new token sniffing tool for it
